# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('created',)},
        ),
    ]
